name: deploy
run-name: Deploy to PyPI

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Build and publish to pypi
          uses: JRubics/poetry-publish@v2.0
          with:
            pypi_token: ${{ secrets.PYPI_TEST_TOKEN }}
            repository_name: "testpypi"
            repository_url: "https://test.pypi.org/legacy/"
